### ISSUE TITLE
3.3V と 5V でLED制御に問題がある

### ISSUE THREAD

**Issue by tkkrr** [Lighting-Mate/lighting_mate#2]
ESP32ではGPIOピンが3.3Vで制御を行なっている。現在自分たちが使っているカラーLEDの必要電圧は4.5~5.5Vであり、電源として5Vを取ったとしてもGPIOの方で制御できない。

- 必要電圧3.3Vの新しいLEDを買う
- 黒魔術で5Vを錬成する

どちらかの対策を取りたい

**Comment by lasurstein** [comment]
3.3V対応のマイコン内蔵LEDは現時点で見当たらない

**Comment by tkkrr** [comment]
3.3Vを5Vにアップコンバートする部品を導入。問題は簡易的に解決した。
理想としては3.3V制御対応のneoPixelLEDが発売されるのを待ち、導入する。
